# Generated by Django 5.0.2 on 2024-03-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hadis_Deryasi', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadis_Deryasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sqlserverconn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField()),
                ('original', models.CharField(max_length=100)),
                ('equivalent', models.CharField(max_length=256)),
                ('second', models.CharField(max_length=100)),
                ('smell', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
