# Generated by Django 5.0.2 on 2024-03-06 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hadis_Deryasi', '0003_hadis_deryasi_home_sqlserverconn_remove_profile_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='FavoritesHadis',
        ),
        migrations.RenameModel(
            old_name='Hadis_Deryasi',
            new_name='HadisDeryasi',
        ),
        migrations.RenameField(
            model_name='sqlserverconn',
            old_name='is_favorite',
            new_name='onay',
        ),
        migrations.RemoveField(
            model_name='sqlserverconn',
            name='equivalent',
        ),
        migrations.RemoveField(
            model_name='sqlserverconn',
            name='original',
        ),
        migrations.RemoveField(
            model_name='sqlserverconn',
            name='second',
        ),
        migrations.RemoveField(
            model_name='sqlserverconn',
            name='smell',
        ),
        migrations.RemoveField(
            model_name='sqlserverconn',
            name='word',
        ),
        migrations.AddField(
            model_name='sqlserverconn',
            name='diger',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sqlserverconn',
            name='diger2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sqlserverconn',
            name='isim',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sqlserverconn',
            name='kelime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sqlserverconn',
            name='koku',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
