# Generated by Django 5.0.3 on 2024-03-07 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hadis_Deryasi', '0004_rename_favorites_favoriteshadis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesWord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HadisDeryasi',
        ),
        migrations.RemoveField(
            model_name='favoriteshadis',
            name='number',
        ),
        migrations.AddField(
            model_name='favoriteshadis',
            name='book',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteshadis',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
