# Generated by Django 5.0.3 on 2024-03-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hadis_Deryasi', '0005_favoritesword_delete_hadisderyasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteshadis',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='favoritesword',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='favoriteshadis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favoritesword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
