# Generated by Django 5.0.3 on 2024-03-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hadis_Deryasi', '0006_favoriteshadis_number_favoritesword_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritesword',
            name='meaning',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sqlserverconn',
            name='kid',
            field=models.IntegerField(null=True),
        ),
    ]
